<?php

$debuggers = $this->getDebuggers();

if (!empty($debuggers)) {
    foreach ($debuggers as $debugger) {
        ob_start();
        var_dump($debugger->getValue());
        $debug = ob_get_clean();
        echo $this->renderTrace($debugger->getTrace()); 
        echo $this->renderCode($debug);
        echo $this->renderSeparator();
     }
} else {
    echo $this->renderLabel('No Debuggers Found...');
}
