<?php

/**
 *    __  _____   ___   __          __
 *   / / / /   | <  /  / /   ____ _/ /_  _____
 *  / / / / /| | / /  / /   / __ `/ __ `/ ___/
 * / /_/ / ___ |/ /  / /___/ /_/ / /_/ (__  )
 * `____/_/  |_/_/  /_____/`__,_/_.___/____/
 *
 * @package FireBug
 * @author UA1 Labs Developers https://ua1.us
 * @copyright Copyright (c) UA1 Labs
 */

namespace UA1Labs\Fire\Bug;

/**
 * This class provides a standard format for Debuggers
 * when a developer calls the debugger() method.
 */
class Debugger
{

    /**
     * The debugger value.
     *
     * @var mixed
     */
    private $value;

    /**
     * The stack trace to the debugger.
     *
     * @var array
     */
    private $trace;

    /**
     * The class constructor.
     */
    public function __construct()
    {
        $this->value = '';
        $this->trace = '';
    }

    /**
     * Set the message value.
     *
     * @param mixed $value The message value
     */
    public function setValue($value)
    {
        $this->value = $value;
    }

    /**
     * Gets the message value.
     *
     * @return mixed
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Sets the trace. Expected value is the array generated by
     * debug_backtrace().
     *
     * @param array<mixed> $trace The array generated by debug_backtrace()
     */
    public function setTrace($trace)
    {
        $this->trace = $trace;
    }

    /**
     * Gets the trace.
     *
     * @return array<mixed>
     */
    public function getTrace()
    {
        return $this->trace;
    }

}
