<?php
    $debuggers = $this->getDebuggers();
?>

<?php if (!empty($debuggers)) { ?>
    <?php foreach ($debuggers as $debugger) { ?>
        <span class="fs-label">
            <?php
                $traces = $debugger->getTrace();
                foreach ($traces as $index => $trace) {
                    $traceLine = '#' . $index . ' ' . $trace['file']
                        . '(' . $trace['line'] . ') ';

                    if (!empty($trace['class'])) {
                        $traceLine .= $trace['class'] . '::';
                    }

                    $traceLine .= $trace['function'] . '()'
                        . '<br>';
                    echo $traceLine;
                }
            ?>
        </span>
        <span class="fs-label">
            <span class="fs-pre-wrap">wrap</span>
            <pre class="debugger"><?php echo var_dump($debugger->getValue()); ?></pre>
        </span>
    <?php } ?>
<?php } else { ?>
    <p>No Debuggers Found...</p>
<?php } ?>
