<?php

/**
 *    __  _____   ___   __          __
 *   / / / /   | <  /  / /   ____ _/ /_  _____
 *  / / / / /| | / /  / /   / __ `/ __ `/ ___/
 * / /_/ / ___ |/ /  / /___/ /_/ / /_/ (__  )
 * `____/_/  |_/_/  /_____/`__,_/_.___/____/
 *
 * @package FireStudio
 * @subpackage FireBug
 * @author UA1 Labs Developers https://ua1.us
 * @copyright Copyright (c) UA1 Labs
 */

namespace Fire\Bug;

/**
 * This class provides a standard format for Debuggers
 * when a developer calls the debugger() method.
 */
class Debugger
{

    /**
     * The debugger message
     * @var mixed
     */
    private $_message;

    /**
     * The stack trace to the debugger.
     * @var array
     */
    private $_trace;

    /**
     * The constructor
     */
    public function __construct()
    {
        $this->_message = '';
        $this->_trace = '';
    }

    /**
     * Set the message value.
     * @param mixed $message The message value
     */
    public function setMessage($message)
    {
        $this->_message = $message;
    }

    /**
     * Gets the message value.
     * @return mixed
     */
    public function getMessage()
    {
        return $this->_message;
    }

    /**
     * Sets the trace. Expected value is the array
     * generated by debug_backtrace().
     * @param array $trace The array generated by debug_backtrace()
     */
    public function setTrace($trace)
    {
        $this->_trace = $trace;
    }

    /**
     * Gets the trace.
     * @return array
     */
    public function getTrace()
    {
        return $this->_trace;
    }

}
